/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.47
 * Generated at: 2013-12-17 20:52:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class Hotellierregistrierung_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/footer_template.jsp", Long.valueOf(1386604537000L));
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write(' ');
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "header_template.jsp" + "?" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("activePage", request.getCharacterEncoding())+ "=" + org.apache.jasper.runtime.JspRuntimeLibrary.URLEncode("Registrierung", request.getCharacterEncoding()), out, false);
      out.write("\n");
      out.write("\n");
      out.write("<div class=\"content\">\n");
      out.write("    <h2>Registrierung</h2>\n");
      out.write("    <form action=\"Hotelregistrierung\" method=\"post\">\n");
      out.write("      <div class=\"form_settings\">\n");
      out.write("\n");
      out.write("        <p><span>Hotelname</span><input type=\"text\" name=\"hotelname\" value=\"\" /></p>\n");
      out.write("        <p><span>Ihr Username</span><input type=\"text\" name=\"username\" value=\"\" /></p>\n");
      out.write("        <p><span>Ihr Vorname</span><input type=\"text\" name=\"vorname\" value=\"\" /></p>\n");
      out.write("        <p><span>Ihr Nachname</span><input type=\"text\" name=\"nachname\" value=\"\" /></p>\n");
      out.write("        <p><span>Email Adresse</span><input type=\"text\" name=\"email\" value=\"\" /></p>\n");
      out.write("        <p><span>Telefonnummer</span><input type=\"text\" name=\"telephone\" value=\"\" /></p>\n");
      out.write("\t\t<p><span>Geschlecht</span><select id=\"id\" name=\"sex\">\n");
      out.write("          <option value=\"0\">Männlich</option> \n");
      out.write("          <option value=\"1\">Weiblich</option>\n");
      out.write("        </select></p>\n");
      out.write("\n");
      out.write("\n");
      out.write("        <p><span>Zimmeranzahl 1 Bett</span><input type=\"text\" name=\"bed1\" value=\"\" /></p>\n");
      out.write("        <p><span>Kosten pro Zimmer 1 Bett</span><input type=\"text\" name=\"cost1\" value=\"\" /></p>\n");
      out.write("        <p><span>Zimmeranzahl 2 Bett</span><input type=\"text\" name=\"bed2\" value=\"\" /></p>\n");
      out.write("        <p><span>Kosten pro Zimmer 2 Bett</span><input type=\"text\" name=\"cost2\" value=\"\" /></p>\n");
      out.write("        \n");
      out.write("\n");
      out.write("        <p><span>Strasse</span><input type=\"text\" name=\"street\" value=\"\" /></p>\n");
      out.write("        <p><span>PLZ</span><input type=\"text\" name=\"zip\" value=\"\" /></p>\n");
      out.write("        <p><span>Ort</span><input type=\"text\" name=\"city\" value=\"\" /></p>\n");
      out.write("        <p><span>Land</span><input type=\"text\" name=\"country\" value=\"\" /></p>\n");
      out.write("\n");
      out.write("         <p><span>Passwort:</span><input type=\"text\" name=\"password1\" value=\"\" /></p>\n");
      out.write("        <p><span>Passwort wiederholen:</span><input type=\"text\" name=\"password2\" value=\"\" /></p>\n");
      out.write("        <p style=\"padding-top: 15px\"><span>&nbsp;</span><input class=\"submit\" type=\"submit\" name=\"name\" value=\"Speichern\" /></p>\n");
      out.write("      </div>\n");
      out.write("    </form>\n");
      out.write("  </div>\n");
      out.write("  \n");
      out.write("\n");
      out.write(" </div>\n");
      out.write("    <footer>\n");
      out.write("      <p>Copyright &copy; scenic_photo | <a href=\"http://www.css3templates.co.uk\">design from css3templates.co.uk</a></p>\n");
      out.write("      <p><h6><a href=\"#\">Sitemap</a>   <a href=\"#\">Impressum</a></h6></p>\n");
      out.write("    </footer>\n");
      out.write("  </div>\n");
      out.write("  <p>&nbsp;</p>\n");
      out.write("  <!-- javascript at the bottom for fast page loading -->\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery.easing-sooper.js\"></script>\n");
      out.write("  <script type=\"text/javascript\" src=\"js/jquery.sooperfish.js\"></script>\n");
      out.write("  <script type=\"text/javascript\">\n");
      out.write("    $(document).ready(function() {\n");
      out.write("      $('ul.sf-menu').sooperfish();\n");
      out.write("    });\n");
      out.write("  </script>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try { out.clearBuffer(); } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
